version: 2.1

orbs:
    docker: circleci/docker@2.2.0

jobs:
    build:
        docker:
            -   image: python:3.7.3-stretch
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum:"requirements.txt" }}
            -   run:
                    name: Install dependencies
                    command: |
                        make setup
                        source ~/.devops/bin/activate
                        make install
            -   save_cache:
                    key:
                        v1-dependecies-{{ checksum:"requirements.txt" }}
                    path:
                        - ~/.devops
            -   run:
                    name: Run lint
                    command: |
                        source ~/.devops/bin/activate
                        make lint
