version: 2.1

jobs:
    build:
        docker:
            -   image: python:3.7.3-stretch
        working_directory: ~/repo
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - v1-deps-{{ checksum "requirements.txt" }}
                        - v1-deps-
            -   run:
                    name: Install dependencies
                    command: |
                        make setup
                        source ~/.devops/bin/activate
                        make install
            -   save_cache:
                    key: v1-deps-{{ checksum "requirements.txt" }}
                    paths:
                        - ~/.devops
            -   run:
                    name: Install hadolint
                    command: |
                        make install-hadolint
            -   run:
                    name: Run lint
                    command: |
                        source ~/.devops/bin/activate
                        make lint
workflows:
    main:
        jobs:
            - build
            -   docker/publish:
                    matrix:
                        parameters:
                            image: [ $DOCKER_USERNAME/khoadd6-devops-capstone-project ]
                            path: [ khoadd6-devops-capstone-project ]
                            docker-context: [ khoadd6-devops-capstone-project ]
                            deploy: [ true ]
                            tag: [ 'v1.0.0' ]
                            update-description: [ true ]
                    reqires: [ build ]
